name: ci
on: push

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - uses: benjavicente/setup-poetry@main
        with:
          poetry-version: 1.1.11

      - name: black
        run: poetry run black --check .

      - name: isort
        run: poetry run isort --check .

      - name: safety
        run: poetry run safety check

      - name: mypy
        run: poetry run mypy . --ignore-missing-imports

  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - uses: benjavicente/setup-poetry@main
        with:
          poetry-version: 1.1.11

      - name: tests
        run: poetry run pytest --asyncio-mode=strict -v --cov=.

      - name: create coverage badge
        run: poetry run coverage-badge > telegramfeed_coverage.svg

      - name: Upload coverage badge to bucket
        uses: zdurham/s3-upload-github-action@master
        if: github.ref_name == 'main'
        with:
          args: --acl public-read
        env:
          FILE: ./telegramfeed_coverage.svg
          AWS_REGION: eu-south-1
          S3_BUCKET: gitbadges.alorenzi.eu
          S3_KEY: telegramfeed_coverage.svg
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
