name: ci
on: push

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - uses: benjavicente/setup-poetry@main
        with:
          poetry-version: 1.1.11

      - name: black
        run: poetry run black --check .

      - name: isort
        run: poetry run isort --check .

      - name: safety
        run: poetry run safety check

      - name: mypy
        run: poetry run mypy . --ignore-missing-imports

  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - uses: benjavicente/setup-poetry@main
        with:
          poetry-version: 1.1.11

      - name: tests
        run: poetry run pytest --asyncio-mode=strict -v --cov=.

      - name: create coverage badge
        run: poetry run coverage-badge > telegramfeed_coverage.svg

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: ./telegramfeed_coverage.svg
          bucket: gitbadges.alorenzi.eu
          bucket-region: eu-south-1
          delete-removed: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
